from __future__ import annotations

import torch
import torch.nn as nn
from .block import EmbeddingBlock, QuarterBlock


class QuarterNet(nn.Module):
    """
    Input: (B, S, Features)
    Output: (B, S, 5)
    """

    def __init__(self, features: int = 9, d_model: int = 4096):
        super().__init__()
        self.embedding = EmbeddingBlock(features, d_model)
        self.quarter1 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter2 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter3 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter4 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter5 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter6 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter7 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter8 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter9 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter10 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter11 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter12 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter13 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter14 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter15 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter16 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter17 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter18 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter19 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter20 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter21 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter22 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter23 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter24 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter25 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter26 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter27 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter28 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter29 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter30 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter31 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)
        self.quarter32 = QuarterBlock(d_model=d_model, num_heads=32, max_seq_len=9696)

        self.cls_tokens = nn.Parameter(torch.zeros(1, 96, d_model))
        nn.init.normal_(self.cls_tokens, std=0.02)
        self.head = nn.Linear(d_model, 5, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.embedding(x)
        cls = self.cls_tokens.expand(x.size(0), -1, -1)
        x = torch.cat([x, cls], dim=1)
        x = self.quarter1(x)
        x = self.quarter2(x)
        x = self.quarter3(x)
        x = self.quarter4(x)
        x = self.quarter5(x)
        x = self.quarter6(x)
        x = self.quarter7(x)
        x = self.quarter8(x)
        x = self.quarter9(x)
        x = self.quarter10(x)
        x = self.quarter11(x)
        x = self.quarter12(x)
        x = self.quarter13(x)
        x = self.quarter14(x)
        x = self.quarter15(x)
        x = self.quarter16(x)
        x = self.quarter17(x)
        x = self.quarter18(x)
        x = self.quarter19(x)
        x = self.quarter20(x)
        x = self.quarter21(x)
        x = self.quarter22(x)
        x = self.quarter23(x)
        x = self.quarter24(x)
        x = self.quarter25(x)
        x = self.quarter26(x)
        x = self.quarter27(x)
        x = self.quarter28(x)
        x = self.quarter29(x)
        x = self.quarter30(x)
        x = self.quarter31(x)
        x = self.quarter32(x)
        x = x[:, -96:, :]
        return self.head(x)
